### ISSUE TITLE
Creo deberíamos usar el mismo formato para subir las carpetas

### ISSUE THREAD

**Issue by DanielRiveraPaniagua** [DanielRiveraPaniagua/Proyecto_ISI#13]
grupo_# o grupo# pero no varios formatos a la vez para que luego sea más fácil a la hora de leer los sql de las carpetas

**Comment by joserequena1998** [comment]
El grupo 3 lo cambiamos a grupo_3. Seguimos todos con grupo_#.

**Comment by DanielRiveraPaniagua** [comment]
Perfecto lo pongo en el README.md y cierro issue
