### ISSUE TITLE
¿Habíamos dicho subir archivos .sql para poder hacer la lectura de los archivos?

### ISSUE THREAD

**Issue by DanielRiveraPaniagua** [DanielRiveraPaniagua/Proyecto_ISI#14]
Lo digo concretamente por el grupo3 de @oscarescuderoarnanz que han subido un .db, por si acaso.

**Comment by oscarescuderoarnanz** [comment]
Lo cambio y lo subo de nuevo, gracias @DanielRiveraPaniagua
