### ISSUE TITLE
Formato de los .sql

### ISSUE THREAD

**Issue by Noozh** [DanielRiveraPaniagua/Proyecto_ISI#17]
Hay que subir los .sql de modo que su primera linea sea:

.open baloncesto.db

De este modo solo tendremos que hacer "sqlite3 < nombredelscript.sql" para incluir las tablas que se pretenden crear con dichos scripts en la base de datos.

**Comment by DanielRiveraPaniagua** [comment]
Estoy de acuerdo con el formato, a ver si alguien más comenta y lo ponemos en los requisitos de los scripts

**Comment by oscarescuderoarnanz** [comment]
Estoy de acuerdo con el nuevo formato, actualizaremos los ficheros.
