### ISSUE TITLE
Grupo 2 y 6 teneis cada uno una tabla pertenecen

### ISSUE THREAD

**Issue by DanielRiveraPaniagua** [DanielRiveraPaniagua/Proyecto_ISI#39]
Creo que solo se diferencian en que una está en mayúscla y la otra en minúscula y eso en realidad es la misma tabla @ismagt @jaime0907

**Comment by Noozh** [comment]
Observando el diagrama me he fijado en que aunque se llaman igual son dos tablas diferentes. Para que no ocurra conflicto cambiamos la nuestra, que relaciona equipos con jugadores, de modo que ahora va a pasar a llamarse adscritos.
