### ISSUE TITLE
Grupo 1 y Grupo 6 ambos teneis una tabla Equipos

### ISSUE THREAD

**Issue by DanielRiveraPaniagua** [DanielRiveraPaniagua/Proyecto_ISI#40]
De hecho creo que son prácticamente iguales @ismagt @dpoloa

**Comment by dpoloa** [comment]
Esa tabla Equipos es propiedad de @ismagt y su grupo, pero la necesitabámos para poder hacer la relación. Cuando creemos las relaciones para las queries, ya no hará falta en la carpeta de nuestro grupo.
