### ISSUE TITLE
Creacion y utilizacion del script de autoejecucion de queries

### ISSUE THREAD

**Issue by Noozh** [DanielRiveraPaniagua/Proyecto_ISI#45]
En el ultimo pull request  #44  que ha realizado el grupo6 hemos incluido un script cuyo proposito es el de autoejecutar TODOS los scripts sql que hemos estado haciendo estos dias (los de creacion y los de insercion).
Para que este script funcione apropiadamente se tienen que cumplir dos cosas.

1. Que las queries de creacion de tablas se encuentren en una carpeta con nombre **_Creacion_tablas_** dentro de la carpeta de vuestro grupo.

2. Que las queries de insercion de registros se encuentren en una carpeta con nombre  _**Inserts**_ dentro de la carpeta de vuestro grupo.

**Comment by DanielRiveraPaniagua** [comment]
Por lo que he visto también hay que quitar .open baloncesto.db de cada tabla?

**Comment by dpoloa** [comment]
Creo que todo esto debería ser comentado en clase con detalle mañana nada más empezar.

**Comment by DanielRiveraPaniagua** [comment]
Completamente de acuerdo

**Comment by mariaffs** [comment]
Nosotros los del "Grupo4" preferimos dejarlo como está, pero bueno, lo que diga la mayoría

**Comment by DanielRiveraPaniagua** [comment]
Usaremos el nuevo script
