### ISSUE TITLE
Revisar pull requests #44 con los cambios de documentación y el nuevo script

### ISSUE THREAD

**Issue by DanielRiveraPaniagua** [DanielRiveraPaniagua/Proyecto_ISI#46]
Está relacionado con el pull #44 y el issue #45. Debería hecharle un vistazo general todos los grupos ya que influye en el nuevo formato y debería aceptarse con mínimo 3 reviews.

**Comment by felipecordente** [comment]
Creo que no hace falta meter los ficheros en carpetas, ni quitar los .open, yo he probado el siguiente scrip y funciona, de esta manera no hay que modificar nada de lo que se especifico al principio.

#!/bin/sh
for i in grupo_*/*.sql
do
   echo $i
   sqlite3 < $i
done

**Comment by DanielRiveraPaniagua** [comment]
Ahora lo hablamos

**Comment by AdrianRiao** [comment]
He probado el script de Felipe y lo único que añadiría sería el globbing a la hora de obtener los ficheros:

#!/bin/sh
for i in grupo_*/*.sql
do
echo $i
sqlite3 < $i
done

Lo he probado y me parece que sí funciona. Quizás es menos engorroso que dividir en carpetas las tablas y los inserts.

Un saludo.

**Comment by AdrianRiao** [comment]
Me estoy fijando que en este editor no se muestran los asteriscos. Quedaría de la siguiente forma:

#!/bin/sh
for i in grupo_#/#.sql
do
echo $i
sqlite3 < $i
done

Donde # equivale a asterisco.

Un saludo.

**Comment by felipecordente** [comment]
Así es Adrián, yo no me había dado cuenta, muchas gracias.

**Comment by DanielRiveraPaniagua** [comment]
```bash
#!/bin/sh
for i in grupo_*/*.sql
do
echo $i
sqlite3 < $i
done
```
En github cuando querais meter codigo es bueno que useís el acento tres veces os paso un link 
https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

Respecto al cambio en el script me parecería bien, esperemos que haya más gente que lo vea. O mejor, abrid un issue si lo creéis conveniente donde venga vuestra proposición
