### ISSUE TITLE
Formato de texto incorrecto en carpeta Grupo 2

### ISSUE THREAD

**Issue by AdrianRiao** [DanielRiveraPaniagua/Proyecto_ISI#49]
Me acabo de fijar que las tablas definidas por el grupo 2 tienen un formato incorrecto. Los nombres de las tablas y sus atributos aparecen con comillas.

Al pasárselo a Sqlite se guardan las tablas pero asumiendo que las comillas están integradas en el nombre.

Un saludo.

**Comment by prodriguezmartinez** [comment]
Vale gracias luego lo cambio :smile:

**Comment by jaime0907** [comment]
Solucionado
